sudo: required
services:
  - docker

before_install:
  - docker build -t ghartwig/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run ghartwig/react-test npm test -- --coverage

after_success:
  - docker build -t ghartwig/multi-client ./client
  - docker build -t ghartwig/multi-nginx ./nginx
  - docker build -t ghartwig/multi-server ./server
  - docker build -t ghartwig/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push ghartwig/multi-client
  - docker push ghartwig/multi-nginx
  - docker push ghartwig/multi-server
  - docker push ghartwig/multi-worker
